### ISSUE TITLE
Errors in Browser Console: 'is not a function'

### ISSUE THREAD

**Issue by tvanalstyne** [w8tcha/CKEditor-CodeMirror-Plugin#100]
I have really enjoyed using the Code Mirror plugin over the last year or so, however, I'm running into issues with a new install. No matter the version of the plugin, I'm getting the following two errors in my browser's console:

![image](https://cloud.githubusercontent.com/assets/8258221/14496496/4cfa208a-0161-11e6-9b59-0c3e8ad8ee35.png)

Any help/ideas would be greatly appreciated. Thank you!

**Comment by w8tcha** [comment]
Did you clear the browser cache before you upgrade, to make sure the browser loads the updates js files?
