### ISSUE TITLE
no obvious way to normalize codemirror content according to ckeditor rules

### ISSUE THREAD

**Issue by kamelkev** [w8tcha/CKEditor-CodeMirror-Plugin#102]
Codemirror allows freeform entry of html, allowing invalid unstructured text to simply be pasted in. A subsequent submit will take this invalid content and pass it into your application.

This is decidedly different than what ckeditor as a whole is designed to do. Specifically ckeditor normalizes all content according to some basic rules.

In my particular case I want to afford a user the ability to enter free form markup, but I want ckeditor to validate that content before I accept it into my application. I can imagine some sort of wrapped API call for getData that would process the content and give me the structure that one would expect.

So for example if someone opens a ckeditor instance, clicks source view and then types "abcdef" I'd want to receive that content wrapped in a <p> tag rather than just accept the raw text into my application.

It's possible there is a way to do this already, if so a note about how to do it would be very useful for people like myself.

**Comment by w8tcha** [comment]
But validating the source content is handled via the editor and not the codemirror plugin. and the editor already do that.

The example you provide with the text insert in to the editor. Then the editor always wrap that in p tag (depends what you set in the config).

All you need is set the config correctly the way you want to filter your or validate your input.

**Comment by kamelkev** [comment]
I'm not sure I understand.

I can enter invalid code into codemirror and there seemingly is no way to trigger it to validate. I know of know what to filter html exactly as ckeditor would except by running the content through CKEditor.

So in my application currently the best proposal is to put up a popup notice every time a customer activates source view and say "please make sure to turn off source view before going to the next page", as this is the only way to get CKEditor to validate the HTML before the input is sent back to the application. Not exactly a great solution, as some users still will forget to do it, or won't understand.

If there is a way to toggle source view on form submit that might be another route. I found exec commands for regular source view toggle, but not for this plugin.

**Comment by w8tcha** [comment]
I understand your problem, but as far as i see there exist no api to trigger the html validation inside the codemirror.
