### ISSUE TITLE
Bower installation

### ISSUE THREAD

**Issue by zuber** [w8tcha/CKEditor-CodeMirror-Plugin#108]
It would be great to install this plugin via bower. There are a couple of forks of this repo in bower, but I (and the most of users, I think) prefer the builds from authors. Thank you!

**Comment by w8tcha** [comment]
Ok i register the package in bower. i hope i do everything correct. the package name is ckeditor-codemirror-plugin

**Comment by zuber** [comment]
The mentioned above package name is already in use, check it on https://bower.io/search/
It refers to https://github.com/souzavitor/ckeditor-codemirror-plugin (I thought earlier it's a fork of this repo...) Can you pick another name for bower?

**Comment by w8tcha** [comment]
okay the new name is codemirror-ckeditor-plugin

**Comment by zuber** [comment]
Thank you, it works just perfect now!
