### ISSUE TITLE
Codemirror sources

### ISSUE THREAD

**Issue by standus** [w8tcha/CKEditor-CodeMirror-Plugin#109]
Hi,
I need extra setting or script which will include my original codemirror sources which already exists in my repository. With this plugin I have duplicated CM sources. I dont want it duplicated. I want upgrade future versions only one directory sources not 2x. I can change plugin to do it, but I dont want change it everytime  after your upgrade.
I think that this will useful for other people.
Thank you.

**Comment by w8tcha** [comment]
tecnically the plugin checks if the CodeMirror is loaded already, and only loads the scripts if needed. But of course if your scripts are loaded after the ckeditor and plugin script then it would be loaded twice.

So the only solution would be a setting
