### ISSUE TITLE
codemirror.min.js is missing in CKEditor-CodeMirror-Plugin.zip 1.16

### ISSUE THREAD

**Issue by Plazik** [w8tcha/CKEditor-CodeMirror-Plugin#112]
File ``codemirror.min.js`` is missing in CKEditor-CodeMirror-Plugin.zip 1.16 https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/releases/download/1.16/CKEditor-CodeMirror-Plugin.zip

1.14 version has it https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/releases/download/v1.14/CKEditor-CodeMirror-Plugin.zip.

**Comment by lynxlynxlynx** [comment]
Confirmed and just symlinking the original works fine.

**Comment by w8tcha** [comment]
thanks i updated the zip package
