### ISSUE TITLE
attributes are going removed?

### ISSUE THREAD

**Issue by kzimny** [w8tcha/CKEditor-CodeMirror-Plugin#114]
- add the class attribute as follow: `<p class="container">This is an example.</p>`
- change to visual designer mode
- open the source code editor again
- class attribute is gone

How to prevent removing the attributes?

**Comment by w8tcha** [comment]
Does this also happen without the CodeMirror plugin? With the standard editor config i can not reproduce the issue

**Comment by kzimny** [comment]
unfortunately yes, attributes in <div></div> are not going removed `<div class="container">test</div>`
attributes placed in <p></p> for instance `<p class="text-center">test</p>` are always removed.
Try yourself: [http://w8tcha.github.io/CKEditor-CodeMirror-Plugin/demoFramed.html](url)

**Comment by w8tcha** [comment]
Yes you are right, but that has nothing to do with the plugin. This is the default behavior of the content filter in the editor.

One option could be to disable the content filter complete.

You can find more about this here... http://stackoverflow.com/questions/15659390/ckeditor-automatically-strips-classes-from-div
