### ISSUE TITLE
limit linelength

### ISSUE THREAD

**Issue by arbyter1** [w8tcha/CKEditor-CodeMirror-Plugin#115]
I often have lines longer than 1000 chars. In such lines the  bracket matching does not work.
Can you make this limit user configurable, or give me a hint, where to alter in source-code.
Thank you for your great work anyway!

**Comment by w8tcha** [comment]
can you describe the steps to reproduce the issue? did you try to disable the setting **autoCloseBrackets**

**Comment by arbyter1** [comment]
why should i disable autoCloseBrackets? It's for this feature, i installed this plugin. 
To  reproduce just enter a line longer then 1000 chars. With 999 chars, it is working, with 1000 not any more.
Mostly the long lines are sql-statements, In these statements no cr and lf are allowed.
I think , the codemirror Plugin is limiting the maxlength to 1000 chars. I didnt find out, where this limit is defined.
here i provide you such a demo line
just paste it and add on more char, then you will see that the brackets no more are highlighted.

{this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)this is a (long line)(long line)}

**Comment by w8tcha** [comment]
Sorry it was a misssunderstanding, you are right this is a config setting..

http://codemirror.net/doc/manual.html#addon_matchbrackets

with the latest commit you can define the line length for scanning in the config

**Comment by arbyter1** [comment]
funny, i cant find a definition of maxScanLineLength in any of the (minified) scripts in the ckeditor plugin. All i can find is 2 occurrence of referenced  maxScanLineLength.

**Comment by w8tcha** [comment]
it is maxScanLines and is in the codemirror.addons.min.js

**Comment by arbyter1** [comment]
snippet  from user manual.
<<maxScanLines
    Stop after scanning this amount of lines without a successful match. Defaults to 1000.
maxScanLineLength
    Ignore lines longer than this. Defaults to 10000.>>

i found only this occurence of maxScanLines  in (unminified) codemirror.addons.min.js 
<<   function f(n, i, u, f, e) {
        for (var h, s, v, c, y, p = e && e.maxScanLineLength || 1e4, a = e && e.maxScanLines || 1e3, l = [], w = e && e.bracketRegex ? e.bracketRegex : /[(){}[\]]/, b = u > 0 ? Math.min(i.line + a, n.lastLine() + 1) : Math.max(n.firstLine() - 1, i.line - a), o = i.line; o != b; o += u)
  >>    

I  have  no idea anymore??

**Comment by w8tcha** [comment]
sorry i dont understand the problem? what happens when you increase the value for maxScanLines?

**Comment by arbyter1** [comment]
i don't find any assignment statement like  "maxScanLines:1000" anywhere, that is my problem. And i think, it should rather be the  maxScanLineLength Parameter. I don't either find this parameter assignment.

**Comment by w8tcha** [comment]
If you can not read the minified code then check the unminified version. It’s all there 

https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/blob/master/codemirror/js/addon/edit/matchbrackets.js

**Comment by arbyter1** [comment]
I dont now how to use  unminified version of the plugin. The filenames do not correspond.
I think, it should be possible to add the parameters in the plugin.js. I tried this:
            var rootPath = this.path,
                defaultConfig = {
                    autoCloseBrackets: true,
                    autoCloseTags: true,
                    autoFormatOnStart: false,
                    autoFormatOnUncomment: true,
                    continueComments: true,
                    enableCodeFolding: true,
                    enableCodeFormatting: true,
                    enableSearchTools: true,
                    highlightMatches: true,
                    indentWithTabs: false,
                    lineNumbers: true,
                    lineWrapping: true,
                    mode: 'htmlmixed',
                    matchBrackets: true,
                    matchTags: true,
                    showAutoCompleteButton: true,
                    showCommentButton: true,
                    showFormatButton: true,
                    showSearchButton: true,
                    showTrailingSpace: true,
                    showUncommentButton: true,
                    styleActiveLine: true,
                    theme: 'default',
                    useBeautifyOnStart: false,
                    maxScanLineLength:10000,
                    maxScanLines:10000
                };

But no effect-- still stopping bracket highlighting  at 1000 chars. I am stuck. 
Did you try it ?

**Comment by arbyter1** [comment]
if have seen you updated the plugin. I downloaded  it, altered the parameters, added even an alert statement, to  make sure, it is loading the new stuff.
But still no effect.  Limit remains at 1000 chars. What i am doing wrong?

**Comment by w8tcha** [comment]
okay i found the problem. i updated the js files. the correct config setting is **maxHighlightLineLength**

**Comment by arbyter1** [comment]
thank you for your update. It works now. 
I am now trying to make work my ctrl-S shortcut to save the content. It is working in wysiwyg mode, but not in the sourcecode view. The plugin catches the keystroke. I would like to pass it over to CKEDITOR. Maybe you can give me a hint?

**Comment by w8tcha** [comment]
Did you define the keystroke via the config?

config.keystrokes = [
    ...
    [ CKEDITOR.CTRL +  115, 'save' ],    // Ctrl+S
    ...
];

the plugin should parse the keystrokes if defined in the config

**Comment by arbyter1** [comment]
it's 
 CKEDITOR.config.keystrokes = 
[
    [ CKEDITOR.CTRL + 83 , 'save' ] /*S*/
];
and it works in wysywig mode.  (my submit function gets called ) 
In sourcode modus,  the keystroke gets trapped, no savedialog from browser appears
but my submit functions does not get called.

**Comment by arbyter1** [comment]
i am still stuck with this question.  ctrl-s does not call the save-function.

**Comment by w8tcha** [comment]
sorry i dont have an idee why it doesnt work, when i remove the line [ CKEDITOR.CTRL + 83 , 'save' ] /S/ the browser dialog appears. it looks like the codemirror blocks the default brower behavoir. This i can not fix

**Comment by w8tcha** [comment]
the only solution would be to use the actually save command in the codemirror.

> but my submit functions does not get called. do you use the save command for that ? can you show me the code so i can try to reproduce it?

**Comment by arbyter1** [comment]
here the sourcecode of my fckeditor - session
[testckeditor.html.txt](https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/files/1234479/testckeditor.html.txt)

and my config file of the plugin
[plugin.js.txt](https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/files/1234485/plugin.js.txt)

hoffe it helps.

By the way: can i honour your work by some bitcoins?

**Comment by arbyter1** [comment]
hi
i  contacted ckeditor support and they told me, that "save was thought to be working in source  code as well"
i  patched ckeditor.js "replace  modes={wysiwyg:!!a.element.$.form}  with  modes={wysiwyg:!!a.element.$.form,source:!!a.element.$.form} 
"
and it  works now  for me.
Next  ckeditor  version should  have this change.

**Comment by w8tcha** [comment]
Okay perfect if that solves the problem
