### ISSUE TITLE
Codemirror with Source Dialog: resize

### ISSUE THREAD

**Issue by blevine** [w8tcha/CKEditor-CodeMirror-Plugin#116]
I am using Codemirror with SourceDialog in CKEditor 4.6.2.  Is there any way to allow the source dialog to be resized?

**Comment by w8tcha** [comment]
I added the feature in the latest commit

**Comment by blevine** [comment]
Looks like this gets us most of the way there.  There's a small bug though.  When you click/drag on the resize handle and start resizing, the height of the dialog "jumps" to a size that is slightly larger than the original height. This is disconcerting and also results in the cursor no longer being positioned over the resize handle.

**Comment by blevine** [comment]
Here is a possible fix.  I'm not very familiar with writing CKEditor plugins, so maybe there's a better way to do this.  I'm taking into account the height of the title area and the height of the footer area.

```
this.on('resize',
  function(event) {
    var parts = event.sender.parts;
    var title = parts.title;
    var footer = parts.footer;
    var holderHeight = (event.data.height - title.$.offsetHeight - footer.$.offsetHeight) + 'px';
    var holderWidth = event.data.width + 'px';
    window["codemirror_" + editor.id].setSize(holderWidth, holderHeight);
  },
  this);
```

**Comment by blevine** [comment]
Nope. Still not sufficient. If you open the source mode dialog, resize it (make sure to make it wider), close the dialog, and then re-open it, you'll see that the dialog retains the resized dimensions, but text only displays at the original dimensions.  This is because the initialization code calculates the initial size based on `CKEDITOR.document.getWindow().getViewPaneSize()` each time the dialog is initialized. So the size of `window["codemirror_" + editor.id]` is forced back to the original size each time the dialog is displayed even though the size of the dialog has changed.

See the code around lines 65-68:

```
var size = CKEDITOR.document.getWindow().getViewPaneSize(),
                        width = Math.min(size.width - 70, 800),
                        height = size.height / 1.5,
```

and line 141:

```
window["codemirror_" + editor.id].setSize(holderWidth, holderHeight);
```

**Comment by w8tcha** [comment]
Okay i found a solution.
