### ISSUE TITLE
Ckeditor not Showing after adding Codemirror Plugin in rails 5.1.3

### ISSUE THREAD

**Issue by Shahbazchandio** [w8tcha/CKEditor-CodeMirror-Plugin#128]
After adding the config.extraPlugins = 'codemirror' in the config.js, the Ckeditor disappears in rails 5

**Comment by w8tcha** [comment]
Are you getting any javascript errors in the browser console?

**Comment by Shahbazchandio** [comment]
console contains many errors like Uncaught ReferenceError: CodeMirror is not defined.

**Comment by Shahbazchandio** [comment]
ncaught TypeError: Cannot read property 'langEntries' of null
    at CKEDITOR.resourceManager.CKEDITOR.plugins.setLang

**Comment by w8tcha** [comment]
Which CKEditor version you are using?

**Comment by w8tcha** [comment]
any update?
