### ISSUE TITLE
In source mode setData() does not set new data

### ISSUE THREAD

**Issue by dajmon** [w8tcha/CKEditor-CodeMirror-Plugin#13]
I am unable to populate editor contents with setData() when in source mode. 
This works fine without the codemirror plugin.

Steps:
1. CKEDITOR.instances.editor.setData('abc');
2. CKEDITOR.instances.editor.setMode('source');
3. CKEDITOR.instances.editor.setData('abcdef');

**Comment by sebhaase** [comment]
This seems broken again .... `this.codeMirror` appears to be undefined in `setData()`
