### ISSUE TITLE
Functions undefined

### ISSUE THREAD

**Issue by jvrdom** [w8tcha/CKEditor-CodeMirror-Plugin#132]
After configure the codemirror plugin, after click on source button have two errors:

![captura de pantalla 2017-12-19 a la s 12 48 17](https://user-images.githubusercontent.com/3360612/34165483-2e1c9c30-e4bb-11e7-85a9-aa6262a2ec08.png)

And cannot go back to the previous view.

I'm using Codemirror 1.17.3 and CKeditor 4.

Any help?

Thanks!

**Comment by w8tcha** [comment]
Which version of the editor you are using? and which browser?

**Comment by jvrdom** [comment]
@w8tcha 4.8.0 of the editor and i'm using Chrome, last version

**Comment by w8tcha** [comment]
Did you use the default codemirror configuration? Atleast with the latest version 1.17.4 and 1.17.3 i can not reproduce the issue
