### ISSUE TITLE
Blinking Â character appears next to the cursor and in empty lines when using latin encoding

### ISSUE THREAD

**Issue by NiavlysB** [w8tcha/CKEditor-CodeMirror-Plugin#136]
When using latin-1/9 encoding (ISO-8859-1 or ISO-8859-15), the blinking cursor is accompanied by a weird "Â" character, blinking as well, which also appears in every empty line (and disappears as soon as you enter any text in this empty line).

## Steps to reproduce
1. Convert the CKeditor demo file `samples/index.html` to ISO-8859-1 (and edit the meta tag to reflect the change)
2. Add `config.extraPlugins = 'codemirror';` to `config.js`, so that the demo uses CodeMirror.
3. Load the demo and switch to source mode.

## Expected result
The blinking cursor should be the same as in a simple textarea, and the empty lines should be empty.

## Actual result
The blinking cursor is accompanied by a `Â` character, which also appears in every empty line.

## Comments
I found this very similar CodeMirror issue: https://github.com/codemirror/CodeMirror/issues/3474

But applying @marijnh's patch (https://github.com/codemirror/CodeMirror/commit/bec937e15e3d62e38e2872721683d0e090eb869a) didn't seem to solve the problem. I looked for other non-ASCII characters in codemirror.min.js, found a U+0080 I think (right before `&&(e.toUpperCase()!=e.toLowerCase()||_l.test(e))`), and tried to replace it with `\u0080`, but it still didn't fix it.

I give up for now, but it should be very easily fixed if one can find where the unescaped non-ASCII character is.

**Comment by NiavlysB** [comment]
Ok, I got it fixed by replacing literal NO-BREAK SPACE (U+00A0) characters with their escaped equivalents: `\u00a0`.

It seems the original space character can't be pasted here, but you can find one before the unique occurrence of `"CodeMirror-cursor"`.

**Comment by w8tcha** [comment]
can you create a pull request with the changes you made?

**Comment by NiavlysB** [comment]
@w8tcha I just tried to do it following your comment, but it seems the issue comes from the minifier, which does its job by minifying `\u00a0` to ` `. The no-break space characters are already escaped in the source file `codemirror.js`: [line 3080](https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/blob/master/codemirror/js/codemirror.js#L3080), [line 3087](https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/blob/master/codemirror/js/codemirror.js#L3087).

**Comment by w8tcha** [comment]
Okay i updated the plugin.js to use the codemirror.js instead of the codemirror.min.js until i figure out how to minify it correctly. Now it should work!

**Comment by fanick1** [comment]
@w8tcha the fix for this issue unfortunately broke the codemirror plugin. Now the output codemirror.js does not include the necessary parts included in the post-processing from grunt and now the require cannot load the codemirror properly (it loads the file from the server, but does not recognize it as the module it was looking for).

**Comment by w8tcha** [comment]
Can you provide an updated gruntfile without the not needed minification? I still dont have a working ckeditor sample with that require js

**Comment by fanick1** [comment]
check PR #141

**Comment by w8tcha** [comment]
thanks!

**Comment by tigrouind** [comment]
I had exact same issue with Parcel. Adding `<meta charset="UTF-8" />` in the head of my index.html file fixed it.
