### ISSUE TITLE
Remove invalid tags

### ISSUE THREAD

**Issue by lkmorlan** [w8tcha/CKEditor-CodeMirror-Plugin#139]
This repository contains two tags that match the revision that they refer to. This causes problems when cloning the repository. Please delete tags `554f371e8ea251f70f857ca0a2d7e49df927c016` and `b329486eab`.

**Comment by w8tcha** [comment]
I don't get any issues when i clone this repository

**Comment by lkmorlan** [comment]
I tried again and this time, I didn't get the error on clone, but it did happen when trying to checkout one of the odd tags:

```
~/CKEditor-CodeMirror-Plugin () $ git checkout 554f371e8ea251f70f857ca0a2d7e49df927c016
warning: refname '554f371e8ea251f70f857ca0a2d7e49df927c016' is ambiguous.
Git normally never creates a ref that ends with 40 hex characters
because it will be ignored when you just specify 40-hex.
```

In any case, I can't imaging that those tags are needed for anything. They look like they were created by accident. Even if they were deleted, checking-out would work because it would do so based on the hash.

**Comment by w8tcha** [comment]
thats odd both commits are regular commits. I don't know why your git tool have problems with them

**Comment by lkmorlan** [comment]
It's not the commits that are the problem. It's the tags. It looks like the names of the tags were intended to be v1.08 and v1.09, but the names of the tags are instead the commit hashes.

**Comment by w8tcha** [comment]
okay i understand both tags are now deleted
