### ISSUE TITLE
JavaScript error for CKEditor 4.9.2

### ISSUE THREAD

**Issue by aik099** [w8tcha/CKEditor-CodeMirror-Plugin#145]
I'm getting this error, when pressing `Source` button in regular (not inline) CKEditor from `samples/index.html` file:

```
TypeError: window[("codemirror_" + b.id)] is undefined[Learn More]
ckeditor.js:776:129
```

I've used https://ckeditor.com/cke4/builder with this `build-config.js`:  [build-config.js.txt](https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/files/1928718/build-config.js.txt)

Just rename attached TXT file in JS and upload in the builder page.

![2018-04-19_1825](https://user-images.githubusercontent.com/1277526/39001524-242a14b6-43ff-11e8-8dda-3ab223046d81.png)

It worked for CKEditor 4.8 using same builder config.

**Comment by aitala** [comment]
I have been having this issue for quite a while >> https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/issues/111#issuecomment-298922863

I'm using this within Drupal 6 & 7 websites using the WYSIWYG module.  It does not seem to be a browser specific issue and the Drupal sites are using different version of jQuery.  The last version that works for me was with CKEditor 4.5.6.91e81fe with D6 .  It does not work in CKE 4.6.2.20af917 with D7.

I will try to add more as I uncover it.

Eric

**Comment by aik099** [comment]
That doesn't sound right. If `codemirror` plugin isn't enabled, then why `codemirror_...` variable is accessed in the first place.

I can see (without any changes), that `codemirror` plugin is enabled, because using `Sourcedialog` plugin opens modal window with HTML syntax highlighted and that's CodeMirror work.

P.S.

The `build-config.js` I've used contains `codemirror` plugin. This way in CKBuilder generated download it's enabled by default.

**Comment by w8tcha** [comment]
I Have no other idea without the ckbuilder this issue is not happening. In that case i remove the plugin from the ckbuilder

**Comment by w8tcha** [comment]
okay i found the problem. You need to remove the sourcearea plugin from the builder then it will work. having both causes the issue

**Comment by aik099** [comment]
Interesting. Everything worked in CKEditor 4.8 with same build config.

I always thought that CodeMirror plugin somehow replaces `Source` button in toolbar (like it integrates with `Sourcedialog` plugin), but looking at it's source code (see https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/blob/master/codemirror/plugin.js#L968-L974) it is adding `Source` button of it's own with same name as `sourcearea` plugin does (see https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/sourcearea/plugin.js#L70-L7).

I wonder why this wasn't causing any conflicts before, but surely it does now.

**Comment by aik099** [comment]
Adding this line to my config solved the problem:

```js
CKEDITOR.config.removePlugins = 'sourcearea';
```

Thank you.

**Comment by aik099** [comment]
Any idea why `Code Mirror` plugin not listed on the builder at https://ckeditor.com/cke4/builder ?

**Comment by w8tcha** [comment]
> I always thought that CodeMirror plugin somehow replaces Source button in toolbar

Actually it duplicates the sourcearea plugin in order to replace the source button, without the ckbuilder the codemirror plugin is loaded before the sourcearea plugin, and it works as expected. But with the CKBuilder the sourcearea plugin is loaded first and the codemirror plugin can't work.

> Any idea why Code Mirror plugin not listed on the builder at https://ckeditor.com/cke4/builder ?

I removed it temp. until i figured out the issue. New version is back online now

**Comment by aitala** [comment]
I will test removing the sourcearea plugin tomorrow and seeing if things work. 

Eric
