### ISSUE TITLE
Feature Request: keep carat position when switching to source view

### ISSUE THREAD

**Issue by frob** [w8tcha/CKEditor-CodeMirror-Plugin#148]
This is a really handy plugin for editing the source of some ckeditor content. It seems to be missing one big feature. When my content editors use the source button on CKEditor they are always frustrated by if forgetting where their cursor was in the page.

Is there anyway to put the carat back where they where when they switch from source to wysiwyg views?

**Comment by w8tcha** [comment]
For that you can use my textselection plug-in

https://ckeditor.com/cke4/addon/textselection
