### ISSUE TITLE
Replace button doesn't work

### ISSUE THREAD

**Issue by mbomb007** [w8tcha/CKEditor-CodeMirror-Plugin#150]
1. I am using this build: https://ckeditor.com/cke4/builder/b400c11b7a97273b57230e270a5e4ac8
2. I am using the CKEditor module version 7.x-1.18 on Drupal 7, though I don't think this is important for reproducing the bug.
3. Open a page with CKEditor for the first time.
	a. If the first button I click is the Find button, the dialog is created and shows just fine.
    -  If I click Replace after this, the dialog will still not show, even though it was created by clicking Find. The behavior is the same as in 3b.

	b. If the first button I click is the Replace button, the semi-transparent layer that normally shows behind the dialog is created, but the dialog itself isn't and never shows. Using browser devtools, I can see that the dialog HTML was never added to the page.
    -  Once I have clicked Replace, due to the overlay being created/shown without the dialog, it is impossible to click anything else.

Removing the codemirror plugin fixes the issue, so it's something with this plugin.

See this issue: https://github.com/ckeditor/ckeditor-dev/issues/2825#issuecomment-466323716

**Comment by w8tcha** [comment]
Thanks for the report. The issue is already fixed. i published version 1.17.10 to the ckbuilder

**Comment by mbomb007** [comment]
Thanks. Is there a corresponding issue number or commit for that fix?

**Comment by w8tcha** [comment]
Yes #149
