### ISSUE TITLE
How to enable and use addons like auto complete through this plugin?

### ISSUE THREAD

**Issue by prakashsvmx** [w8tcha/CKEditor-CodeMirror-Plugin#152]
How to enable and use addons like auto complete through this plugin?
Example
https://codemirror.net/demo/complete.html

**Comment by w8tcha** [comment]
Right now its not included with the plugin, you would need no manually add this.

Is this a function that is needed?

**Comment by prakashsvmx** [comment]
yes. i would like to enable the auto complete functionality in html code editor (when the user switches to source mode). 
any guidance would also be appreciated.

**Comment by w8tcha** [comment]
added in 1.17.11 you only need to enable it via the editor config...

 `config.codemirror = {  mode:{name: "javascript", globalVars: true}`

**Comment by prakashsvmx** [comment]
Great. 💯  Thank you for supporting. i will try and provide feedback.

**Comment by prakashsvmx** [comment]
```
config.codemirror = { mode:{name: "javascript", globalVars: true}}
``` 
i tried with 1.17.11 .

still i do not see the auto complete happening. in the example, there is a function... 
but how do i pass it with config here ?

**Comment by w8tcha** [comment]
Where did you configure the editor config?

i put up a demo:

http://w8tcha.github.io/CKEditor-CodeMirror-Plugin/demoComplete.html

**Comment by prakashsvmx** [comment]
Great thank you for the quick turnout. 
{ mode: { name: 'htmlmixed', globalVars: true }}, //does not work.

{ mode:{name: "javascript", globalVars: true}} // this works fine.

is it safe to assume that it would work if only set to javascript mode ?

**Comment by w8tcha** [comment]
Can you test with html mode with 1.17.12 
https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/releases/tag/v1.17.12

**Comment by prakashsvmx** [comment]
Definitely, i will try and update this.  thank you again.

**Comment by prakashsvmx** [comment]
It displays the autocomplete list of tags. Thank you.
May be it needs fine grained control of what to be displayed as a suggested list. it is available in the original plugin of code-mirror. but not here . Possible enhancement ?

or is it already built in?

**Comment by w8tcha** [comment]
I added the hintOptions option to the config in the latest commit.  You can now parse the options to the plugin
