### ISSUE TITLE
Configure XML Autocomplete with xml-hint

### ISSUE THREAD

**Issue by d7gonzo** [w8tcha/CKEditor-CodeMirror-Plugin#153]
I installed the CodeMirror plugin and set all the options up the way I like. It is working great! Then I noticed the xml-hint addon of CodeMirror and also noticed the core code for it has been added to your repo. How easy would it be to enable this feature in the plugin with a schema produced by [xsd2codemirror](https://github.com/q42jaap/xsd2codemirror)? Any guidance you could provide in how to accomplish this? 

From what I can make out so far, 1) the schemaInfo variable needs to be populated with the json produced by xsd2codemirror, 2) a few extra functions need to be placed to control the hinting functionality, and 3) the editor object needs to be passed the schemaInfo through the hintOptions configuration option along with the keyboard input needed to activate the extra functions. 

Here is the best example from CodeMirror of what I am trying to do within the CKEditor interface: [XML Autocomplete](http://q42jaap.github.io/xsd2codemirror/xsltautocomplete.htm).

**Comment by w8tcha** [comment]
I added support for the addon. you can see the demo here:

https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/blob/master/codemirror/samples/XmlAutoComplete.html
