### ISSUE TITLE
issues with search 

### ISSUE THREAD

**Issue by arbyter1** [w8tcha/CKEditor-CodeMirror-Plugin#155]
hi
i implemented the codeproject ckeditor plugin and find it a very awseom enhancement.
I just found a problem when searching in the source-modus:
ctrl-F opens the searchdialog, entering a search term and hitting enter starts searching, highlilghting all found positions. Ok, so far.
If one hits F3 (default Key for browser search) another searchdialog appears with sometimes correct number of found-hits, sometimes not. Very confusing.

Just using ctrl-F and then ctrl-G to go to the next foundposition seams to work well.
[testcase](https://kinogenossenschaft.chpost.ch/test-search.html)

**Comment by w8tcha** [comment]
Looks like a known issue https://github.com/codemirror/CodeMirror/issues/4766 nothing i can do about
