### ISSUE TITLE
Compatibility with CKEditor 4.15 ?

### ISSUE THREAD

**Issue by jpyrat** [w8tcha/CKEditor-CodeMirror-Plugin#167]
As far I can say, I can't use the builder to download it with https://ckeditor.com/ckeditor-4/download/

**Comment by w8tcha** [comment]
Fixed!

**Comment by jpyrat** [comment]
\o/ That was really fast ! Thanks

**Comment by jpyrat** [comment]
I imagine there is a delay to see it here https://ckeditor.com/cke4/addon/codemirror
and here https://ckeditor.com/ckeditor-4/download/

**Comment by w8tcha** [comment]
> I imagine there is a delay to see it here https://ckeditor.com/cke4/addon/codemirror
> and here https://ckeditor.com/ckeditor-4/download/

What do you mean? you can select the plugin in in the builder when choosing customize
