### ISSUE TITLE
Compatibility with CKEditor 4.16.0

### ISSUE THREAD

**Issue by jpyrat** [w8tcha/CKEditor-CodeMirror-Plugin#169]
As far I can say, I can't use the builder to download it with https://ckeditor.com/ckeditor-4/download/ (again)

**Comment by w8tcha** [comment]
This happens after every new version. After that the plugins have to be updated. You have to wait a few days until i have time to update them.

**Comment by w8tcha** [comment]
Plugin should be available again in the online builder.
