### ISSUE TITLE
Autocomplete further explanation.

### ISSUE THREAD

**Issue by linkrag** [w8tcha/CKEditor-CodeMirror-Plugin#172]
Hi, great plugin. How do i set witch autocomplete language its hinted? Can i add more than one language hint, like HTML and JavaScript? I would like to set custom tags for the hints, i tried changing the html-hint.js with my custom tags (some custom primefaces tags) but it wont show. Appreciente any explanation, thanks.

**Comment by w8tcha** [comment]
Yes multiple languages can be loaded. By default javascript, css, xml and html is loaded.

I think the best way of adding custom hint addons would be by loading the js file separate or modify the plugin.js to load your custom js file.

**Comment by linkrag** [comment]
When i load the htmlmixed on mode, he autocompletes only html/xml tags, i can't make it show any js hints. Do i need to import anything else, or make any alteration? I anexed my code below, do i need to load the plugin.js in my src?

            CKEDITOR.replace('#{cc.clientId}:editor', {
                on: {
                    change: function () {
                        var editorContent = CKEDITOR.instances["#{cc.clientId}:editor"].getData();
                        document.getElementById("#{cc.clientId}:html-value").value = editorContent;
                        if ("#{cc.attrs.onchange}".length > 0) {
                            eval("#{cc.attrs.onchange}");
                        }
                    }
                },
                extraPlugins: 'codemirror',
                startupMode: 'source',
                toolbar: [],
                codemirror: {
                    // Whether or not you want Brackets to automatically close themselves
                    autoCloseBrackets: true,
.
.
.
{as in README}
            });

Then i call it on the page as a component, since i use primefaces. Maybe this is best explained at StackOverFlow?

**Comment by w8tcha** [comment]
> When i load the htmlmixed on mode, he autocompletes only html/xml tags, i can't make it show any js hints. 

You are  right for js hints you need to set the codmirror mode to javascript then it would show js hints..

**Comment by linkrag** [comment]
Returning to the autocomplete function, does the program always use the hints at the hints folder under addons? Or it uses a online repository if i don't import it at the code?

**Comment by w8tcha** [comment]
The add-ons folder is compiled to codemirror.addons.min.js. 

If you want to include additional js files add them to the gruntfile.js and compile it via grunt.

**Comment by linkrag** [comment]
Thanks for the help, i understand better now.
