### ISSUE TITLE
Add a better search UI

### ISSUE THREAD

**Issue by sirtet** [w8tcha/CKEditor-CodeMirror-Plugin#181]
The original search user interface is so basic that it makes the search options hard to learn/use/understand.

To make it more accessible, it might be worth looking into adding something like codemirror-revisedsearch, mentioned in answer 3 here:
https://stackoverflow.com/questions/26230365/how-to-create-search-and-replace-dialog-box-in-codemirror

Other alternative search plugins for CodeMirror:
https://github.com/zhuhs/codemirror-search-replace
https://github.com/bryanchapel/codemirror-modern-search-replace

A minimum-work alternative might be to add a separate icon for search-replace...

**Comment by w8tcha** [comment]
The suggested replacements seems outdated, and none of them does work correctly. So without some work its impossible to replace the existing search.

> A minimum-work alternative might be to add a separate icon for search-replace..

You can already use the standard find / Replace button of the editor when in source mode! But i add an replace button to the source dialog.
