### ISSUE TITLE
styleActiveLine Broken

### ISSUE THREAD

**Issue by aviakrot** [w8tcha/CKEditor-CodeMirror-Plugin#186]

**Comment by w8tcha** [comment]
No description?

**Comment by aviakrot** [comment]
ActiveLine has stopped highlighting the active line

**Comment by w8tcha** [comment]
Is it enabled the in the config?

**Comment by aviakrot** [comment]
Yes. Didn't change anything. Not the current position but the first closing tag is highlighted. (see screenshot https://yadi.sk/i/FV5scMr8T53FsQ )
Broke after upgrading CKeditor to this version https://www.drupal.org/project/ckeditor/releases/7.x-1.22
And I use CDN //cdn.ckeditor.com/4.17.1/full-all

**Comment by w8tcha** [comment]
I dont understand the problem. the active line is highlighted (blue) as expected! What you referring to in the screenshot is the tagmatching feature.

you can see the demo here....

https://codemirror.net/demo/matchtags.html

**Comment by aviakrot** [comment]
I may have mixed up the functions.
I need the cursor to focus in code view mode where I was in edit mode.   It used to be, now I have to look for a place where I was.

**Comment by w8tcha** [comment]
> I may have mixed up the functions. I need the cursor to focus in code view mode where I was in edit mode. It used to be, now I have to look for a place where I was.

Thats a different issue, and for that you need to use my textselection plugin

https://github.com/w8tcha/CKEditor-TextSelection-Plugin

**Comment by aviakrot** [comment]
Thank you! everything started working as it should, although I can't figure out how this feature worked for me before
