### ISSUE TITLE
Missing toolbar icons after using CKEditor builder

### ISSUE THREAD

**Issue by aik099** [w8tcha/CKEditor-CodeMirror-Plugin#193]
When using https://ckeditor.com/cke4/builder the `plugins/codemirror/icons` folder is absent, but images from there are still referenced in the `plugins/codemirror/css/codemirror.min.css` file.

My guess is that the `icons` folder, according to the plugin structure, must contain only toolbar icons used by CKEditor itself, not some custom images, like the ones used by `codemirror` plugin from within the `sourcedialog` plugin, which are now missing after download.

Working (when `codemirror` plugin wasn't built into the CKEditor):

![CKEditor_CodeMirror_ToolbarButtons](https://user-images.githubusercontent.com/1277526/162735911-12c2307d-9190-4493-89cf-910f047684e5.png)

Not working (when `codemirror` plugin was built into the CKEditor):
![CKEditor_CodeMirror_ToolbarButtonsBroken](https://user-images.githubusercontent.com/1277526/162737173-29aa629e-61ba-4ac4-930f-5024e6274634.png)

**Comment by w8tcha** [comment]
I renamed the folder, and updated the version for the ckbuilder

**Comment by aik099** [comment]
Great. Thank you.
