### ISSUE TITLE
CodeMirror Plugin  handlebars syntax highlighting 

### ISSUE THREAD

**Issue by suresh-thanki-phyrem** [w8tcha/CKEditor-CodeMirror-Plugin#202]
I added extraPlugins  "**codemirror** "on ckEditor. It's working fine on source view but  ckEditer **Design/wysiwyg** mode  handlebars syntax highlighting  not working.

**Comment by w8tcha** [comment]
You need to enable the handlebar mode in the editor config

config.codemirror = {
	
	mode: 'handlebars'
};

**Comment by suresh-thanki-phyrem** [comment]
@w8tcha  in codemirror plugin.js I set default mode is handlebars

**Comment by suresh-thanki-phyrem** [comment]
defaultConfig = {
                    autoCloseBrackets: true,
                    autoCloseTags: true,
                    autoFormatOnStart: false,
                    autoFormatOnUncomment: false,
                    autoLoadCodeMirror: true,
                    continueComments: true,
                    enableCodeFolding: true,
                    enableCodeFormatting: true,
                    enableSearchTools: true,
                    highlightMatches: true,
                    indentWithTabs: false,
                    lineNumbers: true,
                    lineWrapping: true,
                    mode: "handlebars",
                    matchBrackets: true,
                    maxHighlightLineLength: 1000,
                    matchTags: true,
                    showAutoCompleteButton: true,
                    showCommentButton: true,
                    showFormatButton: true,
                    showSearchButton: true,
                    showTrailingSpace: true,
                    showUncommentButton: true,
                    styleActiveLine: true,
                    theme: "default",
                    useBeautifyOnStart: false,
                    hintOptions: null,
                    extraKeys: {
						"Ctrl-Space":
                            "autocomplete",
                        "Ctrl-Q": function (codeMirror_Editor) {
                            if (config.enableCodeFolding) {
                                window["foldFunc_" + editor.id](codeMirror_Editor, codeMirror_Editor.getCursor().line);
                            }
                        }
                    }
                };

**Comment by suresh-thanki-phyrem** [comment]
above default config

**Comment by w8tcha** [comment]
> @w8tcha  in codemirror plugin.js I set default mode is handlebars

Then it should work in the source mode of the ckeditor inside codemirror editor.

This plugin does not modify the wysiwyg mode of ckeditor.

**Comment by suresh-thanki-phyrem** [comment]
@w8tcha  Than's for Answer
