### ISSUE TITLE
Open CKEditor in 'source'-Mode breaks Codemirror

### ISSUE THREAD

**Issue by kredmer** [w8tcha/CKEditor-CodeMirror-Plugin#5]
my env:
- jQuery v1.8.3
- CKEditor 4.0 revision 769d96134b
- CodeMirror version 3.0
- "codemirror" plugin, released Dec 29, 2012

If you want the mode at start of ckeditor set to 'source'

``` js
CKEDITOR.replace( 'mytextarea', {
      startupMode: 'source'
   });
```

-> it will break with following error: "ReferenceError: CodeMirror is not defined"

Problem located in [plugin.js](https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/blob/master/codemirror/plugin.js) line 29:

``` js
CKEDITOR.scriptLoader.load(rootPath + 'js/codemirror.js', function (success) {
                CKEDITOR.scriptLoader.load([rootPath + 'js/xml.js', rootPath + 'js/javascript.js', rootPath + 'js/css.js', rootPath + 'js/htmlmixed.js']);
            });
```

So I tried to load the needed scripts with page load:

``` html
<script type="text/javascript" src="/assets/ckeditor/plugins/codemirror/js/codemirror.js?body=1">
<script type="text/javascript" src="/assets/ckeditor/plugins/codemirror/js/xml.js?body=1">
<script type="text/javascript" src="/assets/ckeditor/plugins/codemirror/js/javascript.js?body=1">
<script type="text/javascript" src="/assets/ckeditor/plugins/codemirror/js/css.js?body=1">
<script type="text/javascript" src="/assets/ckeditor/plugins/codemirror/js/htmlmixed.js?body=1">
```

-> now the source-content in CKEditor is empty !!!
Pressing two times the source-button makes codemirror work !

My workaround till this problem exists:

``` js
CKEDITOR.replace( 'mytextarea', {
    on: {
        instanceReady: function() {
            this.setMode('source'); 
        }},
      startupMode: 'wysiwyg'
   });
```

With this workaround the scriptloader will work - you will see for a short time the ''wysiwyg'-mode and then the highlighted code.

problem:
the "exec: function (editor)" of CKEDITOR.plugins.sourcearea is called first after pressing the source-button

possible Solution:
move the first call in init function

I found this page: http://rondvorak.com/browse/browse/ckeditor-codemirror/
The implementation (with older code) is here with adding a plugin instead of overwriting.....but it looks also if first the 'wysiwyg'-mode is called....

**Comment by ozboluk1** [comment]
Tnx bro
