### ISSUE TITLE
How to add Html Embedded Scripts support in CKEditor plugin

### ISSUE THREAD

**Issue by ruifortes** [w8tcha/CKEditor-CodeMirror-Plugin#56]
Hello.
I just installed codemirror ckeditor plugin and everithing works fine except I can't use 'application/x-aspx' mode. I notice that in the plugins folder theres a 'codemirror.mode.htmlmixed.min.js' file but no 'codemirror.mode.htmlembedded.min.js'
Is it possible to add this functionality in ckeditor plugin?
Thanks

**Comment by thedarkside** [comment]
I used the `application/x-ejs` mode in an earlier version but in version 1.13 its suddenly broken now.
Getting `TypeError: a.multiplexingMode is not a function` in the Firefox console.

**Comment by w8tcha** [comment]
Fixed in latest commit.
