### ISSUE TITLE
Unwanted code being added after toggling between views

### ISSUE THREAD

**Issue by EOEfrance** [w8tcha/CKEditor-CodeMirror-Plugin#69]
Hello w8tcha,

In toggling between source and preview mode some unwanted code is being added automatically. When I am in the source mode I’ll put my cursor anywhere outside actual text content and then click over to preview mode. When I click back over to source code there would either be paragraph tags or an entire table row added. I delete the unwanted code and it reappears after toggling back and forth between views.
 
In this example video capture I put my cursor at the end of a closing table row tag and when I toggle between views you’ll see that a new, additional table row is added.
http://images.eyesonemail.com/GRissues/CKeditorAddingTR&TDtags.mov
 
In this example I put the cursor at the end of the opening table tag and when I toggle between views an opening and closing tbody tag and new row is added automatically.
http://images.eyesonemail.com/GRissues/CKeditorAddingTbody&TDtags.mov
 
If I put my cursor inside content text before toggling between views then everything seems to be ok. I’ve validated my HTML and the structure is intact and not missing any opening or closing tags.
 
Have you seen this before with your plugin?

Let me know if you can see the videos. I’d love some guidance on what might be happening here. My system is developed by a separate team who implemented CKeditor and who is using your plugin.
We're using CKeditor 4.4.3

Thank you. Let me know what other details you may need.

Dan Lavelle
EyesOnEmail.com

**Comment by w8tcha** [comment]
This issue is fixed with commit https://github.com/w8tcha/CKEditor-TextSelection-Plugin/commit/4f4f00b7c8f59c9ca784090ece1062fd0b30c665 from the textselection plugin
