### ISSUE TITLE
amd/requirejs breaks loading

### ISSUE THREAD

**Issue by davhdavh** [w8tcha/CKEditor-CodeMirror-Plugin#73]
If you use requirejs or similar in your project and then load CodeMirror through the plugin, the load fails because CodeMirror does not get defined in window.

**Comment by davhdavh** [comment]
Yes,

I edited the codemirror.min.js and inserted this at the top
var a = "function"==typeof define&&define.amd ? define : null;
if (a) define = null;

and this after
if (a) define = a;

That temporarily disables amd while loading the module, and thus just
defined CodeMirror in global namespace.


On Thu, Jan 8, 2015 at 9:49 AM, Andrew Boni <notifications@github.com>
wrote:

> Also running into this issue. @davhdavh <https://github.com/davhdavh> did
> you manage to come up with a solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/issues/73#issuecomment-69128707>
> .
>



-- 
Dennis

**Comment by andrewboni** [comment]
As per your suggestion, in `codemirror.min.js` I have:
```javascript
var a = "function"==typeof define&&define.amd ? define : null;
if (a) define = null;
(function(a){if(typeof exports == "object"...
if (a) define = a;
```
but `CodeMirror` is still `undefined` globally.

My requirejs config:
```coffeescript
paths:
  ...
     ckeditor               : "lib/ckeditor-4.4.6/ckeditor"
    "ckeditor-codemirror"   : "lib/ckeditor-4.4.6/plugins/codemirror/plugin"
  ...
shim:
  ...
    ckeditor:
      exports: 'CKEDITOR'
      deps: ['jquery']
    "ckeditor-codemirror":
      exports: 'CodeMirror'
      deps: ['jquery', 'ckeditor']
  ...
```

And I am including the modules in my `define` statement:
```coffeescript
define(['ckeditor', 'ckeditor-codemirror'...], (CKEDITOR, CodeMirror) -> ...
```

FWIW, I am using CKeditor 4.4.6 and Codemirror plugin 1.12. Any thoughts @davhdavh? Thanks!

**Comment by davhdavh** [comment]
I wrote BEFORE and AFTER... Look at what the script actually does

On Fri, Jan 9, 2015 at 2:58 AM, Andrew Boni <notifications@github.com>
wrote:

> As per your suggestion, in codemirror.min.js I have:
>
> var a = "function"==typeof define&&define.amd ? define : null;if (a) define = null;
> (function(a){if(typeof exports == "object"...if (a) define = a;
>
> but CodeMirror is still undefined globally.
>
> My requirejs config:
>
> paths:
>   ...
>      ckeditor               : "lib/ckeditor-4.4.6/ckeditor"
>     "ckeditor-codemirror"   : "lib/ckeditor-4.4.6/plugins/codemirror/plugin"
>   ...shim:
>   ...
>     ckeditor:
>       exports: 'CKEDITOR'
>       deps: ['jquery']
>     "ckeditor-codemirror":
>       exports: 'CodeMirror'
>       deps: ['jquery', 'ckeditor']
>   ...
>
> And I am including the modules in my define statement:
>
> define(['ckeditor', 'ckeditor-codemirror'...], (CKEDITOR, CodeMirror) -> ...
>
> FWIW, I am using CKeditor 4.4.6 and Codemirror plugin 1.12. Any thoughts
> @davhdavh <https://github.com/davhdavh>? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/issues/73#issuecomment-69238981>
> .
>



-- 
Dennis

**Comment by andrewboni** [comment]
I was able to get @davhdavh's suggestion  to work, but only after setting `config.codemirror.enableCodeFolding: false`, as it was failing on this line:
```javascript

window["foldFunc_" + editor.id] = CodeMirror.newFoldFunction(CodeMirror.tagRangeFinder);
                                             ^^^^^
```

```
Uncaught TypeError: undefined is not a function
```

Not 100% sure why, but hopefully this helps someone else.

Using plugin version `1.12` and codemirror version `4.10.0`

**Comment by andrewboni** [comment]
Actually, seems like not everything works- only line numbers and some basic code font formatting work:

![screenshot 2015-01-12 19 20 19](https://cloud.githubusercontent.com/assets/255026/5715575/2d947292-9a90-11e4-8dac-7d7e50973d74.png)

Everything else- `theme`, `matchBrackets`, `autoCloseTags`, searching, etc don't seem to work. 

No console errors occur when toggling in and out of source mode. Both `CKEDITOR` and `CodeMirror` are defined globally in the browser.

Trying to do a find results in `Uncaught TypeError: undefined is not a function` for
```javascript
CodeMirror.commands.find(window["codemirror_" + editor.id]);
```

Seems that the `find` method is not working properly?

![screenshot 2015-01-12 19 26 30](https://cloud.githubusercontent.com/assets/255026/5715605/ee1ad5ec-9a90-11e4-95f1-de6a81d5d1d1.png)

Any light shed on this issue is definitely appreciated!

**Comment by davhdavh** [comment]
It will only help in a compiled codemirror, not a debug version.
In the debug version, it uses require to load the missing plugins, whereas
in the release minified copy, they are all packaged in the same file already

On Tue, Jan 13, 2015 at 10:27 AM, Andrew Boni <notifications@github.com>
wrote:

> Actually, seems like not everything works- only line numbers and some
> basic code font formatting work:
>
> [image: screenshot 2015-01-12 19 20 19]
> <https://cloud.githubusercontent.com/assets/255026/5715575/2d947292-9a90-11e4-8dac-7d7e50973d74.png>
>
> Everything else- theme, matchBrackets, autoCloseTags, searching, etc
> don't seem to work.
>
> No console errors occur when toggling in and out of source mode. Both
> CKEDITOR and CodeMirror are defined globally in the browser.
>
> Trying to do a find results in Uncaught TypeError: undefined is not a
> function for
>
> CodeMirror.commands.find(window["codemirror_" + editor.id]);
>
> Seems that the find method is not working properly?
>
> [image: screenshot 2015-01-12 19 26 30]
> <https://cloud.githubusercontent.com/assets/255026/5715605/ee1ad5ec-9a90-11e4-95f1-de6a81d5d1d1.png>
>
> Any light shed on this issue is definitely appreciated!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/issues/73#issuecomment-69690347>
> .
>



-- 
Dennis
