### ISSUE TITLE
Right click required

### ISSUE THREAD

**Issue by Agux** [w8tcha/CKEditor-CodeMirror-Plugin#78]
It seems the right-click event is being swallowed by CodeMirror plugin. 

You can reproduce on the demo page:
http://w8tcha.github.io/CKEditor-CodeMirror-Plugin/demoFramed.html

Right-clicking on source mode will produce no context menu. What I'm looking for is the browser default context-menu. 

Am I missing some sort of setting ? I tried looking at the plugin source code, but I can't find the sweet spot for this.

Please advise !
Cordially, Agustin.

**Comment by w8tcha** [comment]
This issue should be already fixed with the latest version, See #9 for more info. I updated the Demo Page with the latest version
