### ISSUE TITLE
Slash while in source mode?

### ISSUE THREAD

**Issue by larsinsd** [w8tcha/CKEditor-CodeMirror-Plugin#79]
I'm having a problem with CKEditor 4.4.6 with TextSelection and the latest version of CodeMirror not allowing me to type a slash while in Source mode.  Am I the only one with this problem?  I noticed you made some changes in closetag.js that may be the culprit?

**Comment by kevjames3** [comment]
I am having a similar issue - However, I can still replicate the bug on the demo (http://w8tcha.github.io/CKEditor-CodeMirror-Plugin/demoFramed.html).   Does that mean that the demo is not updated to the most recent or does the problem still persist?
