### ISSUE TITLE
problem with new line

### ISSUE THREAD

**Issue by bjbmedia** [w8tcha/CKEditor-CodeMirror-Plugin#81]
if you open the sourcedialog on http://w8tcha.github.io/CKEditor-CodeMirror-Plugin/demoInline.html and press [enter] a few times in the codemirror-dialog, new lines get messed up and the cursor is not where it should be

![codemirror_01](https://cloud.githubusercontent.com/assets/11886691/7087762/e5b9328e-df8e-11e4-9377-24d63394e4d3.jpg)

problems seems to be that the [span] element after [pre] should be {white-space: pre}, but has been changed by 

.cke_reset_all .CodeMirror-scroll * to {white-space: normal}

so if you change .cke_reset_all .CodeMirror-scroll * to {white-space: pre} everything works as it should and [enter] creates a visible new line

![codemirror_02](https://cloud.githubusercontent.com/assets/11886691/7087771/fd1e8f1e-df8e-11e4-8cfa-4639ea28b0ad.jpg)

best regards

Bernd

**Comment by w8tcha** [comment]
Thanks
