### ISSUE TITLE
CodeMirror hides inline editor toolbar

### ISSUE THREAD

**Issue by andrewvaca** [w8tcha/CKEditor-CodeMirror-Plugin#82]
Hi,

thanks for great plugin. I just found, when you use it on inline CKEditor with Source Dialog plugin, after changing the source code and submiting the dialog, the CKEditor toolbar disapears. Clickin to the editor won't help. You can click elsewhere on the page and back to the editor (lost and regain focus), but it's annoying.

You can try it even on your demo. I'm using Safari 8.0.5 on OSX 10.10.3, CK Editor 4.4.7 and CodeMirror 1.12
![screenshot 2015-04-15 10 22 33](https://cloud.githubusercontent.com/assets/7955240/7154956/1fc0ae06-e35b-11e4-95c5-ce391ae4a4ba.png)
![screenshot 2015-04-15 10 22 54](https://cloud.githubusercontent.com/assets/7955240/7154966/287d7524-e35b-11e4-8cca-7ed7275fc8c3.png)

**Comment by w8tcha** [comment]
Does this also happens with the regular sourcedialog plugin?

**Comment by andrewvaca** [comment]
No, it happens only in combination of SourceDialog http://ckeditor.com/addon/sourcedialog, CodeMirror plugin and inline editor (the standard editor is fine).

**Comment by w8tcha** [comment]
Sorry but in that case you have to live with it, i don't have a mac an i'm unable to test or fix this without a mac.

**Comment by ddddd099** [comment]
I have the same situation in Mozilla, Chrome.

**Comment by Kipperlenny** [comment]
Same problem on Windows with Chrome Version 53.0.2785.116 and below. Can be reproduced in your official demo
