### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toolbar' of undefined

### ISSUE THREAD

**Issue by jonathanbull** [w8tcha/CKEditor-CodeMirror-Plugin#83]
If I add CodeMirror to the standard preset in the CKBuilder [builder](http://ckeditor.com/builder), I get the following issue:

`Uncaught TypeError: Cannot read property 'toolbar' of undefined (ckeditor.js:966).`

Any ideas?

**Comment by w8tcha** [comment]
Did you add or removed anything else?

I used the standard preset and added only codemirror and everything works as expected.
