### ISSUE TITLE
the whole code is replaced with - sign only using chrome

### ISSUE THREAD

**Issue by AleksanderKuc** [w8tcha/CKEditor-CodeMirror-Plugin#84]
chrome version: 43.0.2357.124 m
os: windows 7
How to reproduce:
1. Go to http://w8tcha.github.io/CKEditor-CodeMirror-Plugin/demoFramed.html using chrome
2. copy&paste content so the vertical scroll bar shows
![1a](https://cloud.githubusercontent.com/assets/8465007/8106405/4d862948-1041-11e5-95cd-8cc152c21d56.PNG)
3. select all (ctrl+A)
4. turn on full screen mode with button
![2](https://cloud.githubusercontent.com/assets/8465007/8106410/55998030-1041-11e5-9e3d-6402218a64ab.PNG)

Please help, maybe by providing some code hints how to fix this issue.

**Comment by w8tcha** [comment]
At least with the latest version of chrome i no longer can reproduce the issue.
