### ISSUE TITLE
Ver 4.5.1 bug in source view

### ISSUE THREAD

**Issue by mlandmann** [w8tcha/CKEditor-CodeMirror-Plugin#86]
CodeMirror (Source) Syntax Highlighting plugin 

in version 4.5.1, in the source view mode, I am getting: 

InvalidCharacterError: String contains an invalid character 

nothing happens when you click on the source button.

In the source dialog mode however, it appears to work.

**Comment by sdebacker** [comment]
Same problem for me

**Comment by zabbarob** [comment]
the error described above is fixed in c4a2019600b46a1be334dc65a47893b219c92e83 but the plugin's not updated on ckeditor.com, in other words using the github-version works.

however, there is another message on the debug console: `Uncaught ReferenceError: textRange is not defined` which is because of [line 886 in plugin.js](https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/blob/master/codemirror/plugin.js#L886): `if (editor.plugins.textselection && textRange) {`

I guess that maybe this should be the range computed during the `beforeModeUnload` event, but `textRange` is not set anywhere:

```javascript
            editor.on('beforeModeUnload', function (evt) {
                if (editor.mode === 'source' && editor.plugins.textselection) {

                    var range = editor.getTextSelection();

                    range.startOffset = LineChannelToOffSet(window["codemirror_" + editor.id], window["codemirror_" + editor.id].getCursor(true));
                    range.endOffset = LineChannelToOffSet(window["codemirror_" + editor.id], window["codemirror_" + editor.id].getCursor(false));

                    // Fly the range when create bookmark. 
                    delete range.element;
                    range.createBookmark(editor);
                    sourceBookmark = true;

                    evt.data = range.content;
                }
            });
            editor.on('mode', function () {
                editor.getCommand('source').setState(editor.mode === 'source' ? CKEDITOR.TRISTATE_ON : CKEDITOR.TRISTATE_OFF);

                if (editor.mode === 'source') {
                    editor.getCommand('autoCompleteToggle').setState(window["codemirror_" + editor.id].config.autoCloseTags ? CKEDITOR.TRISTATE_ON : CKEDITOR.TRISTATE_OFF);

                    if (editor.plugins.textselection && textRange) {

                        //textRange.element = new CKEDITOR.dom.element(editor._.editable.$);
                        //textRange.select();
...
```

**Comment by w8tcha** [comment]
> InvalidCharacterError: String contains an invalid character

Fixed in CodeMirror Version 1.13

**Comment by mlandmann** [comment]
Awesome.  Thanks for the quick fix!

**Comment by mlandmann** [comment]
Hate to say it, but after downloading 1.13 the same error I reported at the very top is there.
Check on IE and FF.

**Comment by w8tcha** [comment]
Did you clear the browser cache?

**Comment by mlandmann** [comment]
Yes.  I tried it on both IE and FF.  I downloaded it again to make sure I had the right version.  I deleted the source plugin in CK and added back the complete code I down load.

 

Mark Landmann

Support

Office: 303-470-1928

Mobile: 303-883-6196

Skype: mlandmann1

**Comment by w8tcha** [comment]
I tested it with firefox & IE both without any issues. Can you post your editor config?

**Comment by w8tcha** [comment]
Does the demo work?

http://w8tcha.github.io/CKEditor-CodeMirror-Plugin/demoFramed.html

**Comment by zabbarob** [comment]
demo works for me (didn't yet have time to try out v1.13 in my system), but it still spits out two error message about calling `closeTag` function, when i delete the final `>` and then enter `/>` in the editor:

![screen shot 2015-07-09 at 13 29 53](https://cloud.githubusercontent.com/assets/419922/8594230/471cda98-263f-11e5-9f48-c7088dc462fc.png)

**Comment by mlandmann** [comment]
Yes, that works.  It works in IE and FF.  It comes up in the source view mode – but that is probably something in the demo you sent to come up that way.  But it works, I can see the source and do not see any JS errors.

 

 

Mark Landmann

Support

Office: 303-470-1928

Mobile: 303-883-6196

Skype: mlandmann1

**Comment by w8tcha** [comment]
> but it still spits out two error message about calling closeTag function, when i delete the final > and then enter /> in the editor

Fixed in latest commit, but please report different errors in new issue reports

**Comment by mlandmann** [comment]
OK, so it comes down to this there is something in the configuration that I built is different than what you use.  Your ckeditordemoo works, mine fails.  

I downloaded your latest and ran it against my CKEditor July 2 4.5.1 build.  Failed -- same error.  I downloaded your version of ckeditor -- ran fine.  So there is something in the custom build that I made (or didn't do that is causing a problem).

Below is my build config:build-config.js.  I am not sure that you want to solve my problem, and there are endless permutations of builds one can make with different includes, but here is what I did.  It appears that at least 1 other person on this thread is having the same issue.   thank you!!!
--------------------------------------------------------------------------------------------------
﻿/**
 * @license Copyright (c) 2003-2015, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

/**
 * This file was added automatically by CKEditor builder.
 * You may re-use it at any time to build CKEditor again.
 *
 * If you would like to build CKEditor online again
 * (for example to upgrade), visit one the following links:
 *
 * (1) http://ckeditor.com/builder
 *     Visit online builder to build CKEditor from scratch.
 *
 * (2) http://ckeditor.com/builder/caac96ece1ac65db1171ee1884dc2617
 *     Visit online builder to build CKEditor, starting with the same setup as before.
 *
 * (3) http://ckeditor.com/builder/download/caac96ece1ac65db1171ee1884dc2617
 *     Straight download link to the latest version of CKEditor (Optimized) with the same setup as before.
 *
 * NOTE:
 *    This file is not used by CKEditor, you may remove it.
 *    Changing this file will not change your CKEditor configuration.
 */

var CKBUILDER_CONFIG = {
	skin: 'Moono_blue',
	preset: 'full',
	ignore: [
		'.bender',
		'bender.js',
		'bender-err.log',
		'bender-out.log',
		'dev',
		'.DS_Store',
		'.editorconfig',
		'.gitattributes',
		'.gitignore',
		'gruntfile.js',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'less',
		'.mailmap',
		'node_modules',
		'package.json',
		'README.md',
		'tests'
	],
	plugins : {
		'a11yhelp' : 1,
		'about' : 1,
		'autocorrect' : 1,
		'autogrow' : 1,
		'autolink' : 1,
		'autosave' : 1,
		'backgrounds' : 1,
		'basicstyles' : 1,
		'bidi' : 1,
		'blockquote' : 1,
		'clipboard' : 1,
		'codemirror' : 1,
		'colorbutton' : 1,
		'colordialog' : 1,
		'contextmenu' : 1,
		'dialogadvtab' : 1,
		'div' : 1,
		'elementspath' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'filebrowser' : 1,
		'find' : 1,
		'flash' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'format' : 1,
		'forms' : 1,
		'horizontalrule' : 1,
		'htmlwriter' : 1,
		'iframe' : 1,
		'image' : 1,
		'image2' : 1,
		'imageresize' : 1,
		'indentblock' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'language' : 1,
		'link' : 1,
		'list' : 1,
		'liststyle' : 1,
		'magicline' : 1,
		'maximize' : 1,
		'newpage' : 1,
		'pagebreak' : 1,
		'pastefromword' : 1,
		'pastetext' : 1,
		'preview' : 1,
		'print' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'save' : 1,
		'scayt' : 1,
		'selectall' : 1,
		'showblocks' : 1,
		'showborders' : 1,
		'smiley' : 1,
		'sourcearea' : 1,
		'sourcedialog' : 1,
		'specialchar' : 1,
		'stylescombo' : 1,
		'tab' : 1,
		'table' : 1,
		'tableresize' : 1,
		'tabletools' : 1,
		'templates' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'videodetector' : 1,
		'widgetcommon' : 1,
		'wsc' : 1,
		'wysiwygarea' : 1,
		'xmas' : 1,
		'youtube' : 1,
		'zoom' : 1
	},
	languages : {
		'en' : 1
	}
};

**Comment by mlandmann** [comment]
Sorry I did not mean to shout in the above message.  The font looked ok when enter here and is huge when displayed!

**Comment by w8tcha** [comment]
I tried your build open up ...\samples\index.html no errors with IE 11 and firefox 40

**Comment by mlandmann** [comment]
Can you send me you build-config.js file you used for you demo, please.

I've got to get this fixed.  Knowing what you included will be the base to add to where I need features.

 

 

Mark Landmann

Support

Office: 303-470-1928

Mobile: 303-883-6196

Skype: mlandmann1

**Comment by w8tcha** [comment]
build config is included with the demo, but it is just the full download package and codemirror manually added.

https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/blob/gh-pages/ckeditor/build-config.js

**Comment by mlandmann** [comment]
I spent hours downloaded and rebuilding the new version and it now works.  I believe there is still a conflict with one of the add in I previously added in.

 

I have another question.  What are the styles and where do I modify them for Autosave and other notifications

 

I see :



 

Or 



 

The demos are nicely styled in a box.  And I am pulling my hair out trying to find the css or where this is defined.  Can you help?

Thank you!!

 

Mark Landmann

Support

Office: 303-470-1928

Mobile: 303-883-6196

Skype: mlandmann1

**Comment by w8tcha** [comment]
> The demos are nicely styled in a box.  And I am pulling my hair out trying to find the css or where this is defined.  Can you help?

The Demos are designed with bootstap http://getbootstrap.com
