### ISSUE TITLE
Prevent Codemirror from changing code structure

### ISSUE THREAD

**Issue by Perpicx** [w8tcha/CKEditor-CodeMirror-Plugin#87]
When I use Codemirror within CKEditor, I want my own structure for the source code for better viewing and seprating code blocks. But when I change form source view to WYSIWYG and back Codemirror always sets the code back to one line wihtout separated lines.

How can I prevent this?

**Comment by w8tcha** [comment]
Can you post some sample code so i can try to reproduce it?

Technically the "autoFormatOnStart" setting is disabled by default

**Comment by seadil** [comment]
I'm using codemirror with Drupal (WYSIWYG module + ckeditor).
My config.js looks like this:

CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here. For example:
	// config.language = 'fr';
	// config.uiColor = '#AADC6E';
    config.codemirror = {
        theme: eclipse,
        autoFormatOnStart: true,
        useBeautify: true
    }
};

**Comment by w8tcha** [comment]
i already posted the solution above. change lines

autoFormatOnStart: true,
useBeautify: true

to

autoFormatOnStart: false,
useBeautify: false

**Comment by seadil** [comment]
It's not working.
Is there a way to check if config.js is being even used? It seems to me that Drupal ignores my config file.

**Comment by w8tcha** [comment]
Well that is just the default config, is guess it is loaded dynamically loaded in drupal. But i can not help you with that.

**Comment by yllumi** [comment]
I get the same problem. If I set the config like this

autoFormatOnStart: false,
useBeautify: false

all the lines of code will begin in column 1, and remove all my current indentation.
Can I prevent CKEditor to maintain the current indentation?
