### ISSUE TITLE
CKEditor with CodeMirror fires no "key" event in source mode.

### ISSUE THREAD

**Issue by dsuckau** [w8tcha/CKEditor-CodeMirror-Plugin#88]
Hey,

when I enable the CodeMirror Plugin, the "key" event CKEditor will not be fired in source mode anymore, only in normal mode.

Examples:

    var editor = CKEDITOR.replace(document.querySelector('textarea'), {
        width: 900,
        height: 400,
    });

    editor.on('key', function () {
        console.log('key event')
    });

Press keys in normal mode: console.log messages appear
Press keys in source mode: console.log messages appear

    var editor = CKEDITOR.replace(document.querySelector('textarea'), {
        extraPlugins: 'codemirror',
        width: 900,
        height: 400,
    });

    editor.on('key', function () {
        console.log('key event')
    });

Press keys in normal mode: console.log messages appear
Press keys in source mode: console.log messages do NOT appear

Is that a known behavior or even on purpose? Or is it a bug?

Greets

**Comment by w8tcha** [comment]
the event can not be inherited from the codemirror. You would use the codemirror keypress event..

```javascript
window["codemirror_" + editor.id].on("keypress", function (codeMirror_Editor, evt) {
                    console.log('key event');
                });
```

**Comment by dsuckau** [comment]
Thank you, that was the point.
