### ISSUE TITLE
CodeMirror Source Remains at Full Width After Minimize When Inside Tables

### ISSUE THREAD

**Issue by henweigh** [w8tcha/CKEditor-CodeMirror-Plugin#89]
Hello,

I discovered an odd issue with the CodeMirror plugin when CKEditor resides within a table cell. If the user maximizes the source view and then minimizes it, the width of the source view will remain 100% of the page until the user switches back and forth between source/design views.

To reproduce the error:
1. Load up CKEditor with CodeMirror Plugin
2. Click the source button
3. Maximize the editor (using the maximize button)
4. Minimize (restore) the editor to default size (using the maximize button)

You will see the window remains at 100% doc width.

The only workaround I've found is to click the source button two times to reset the width.

I set up a page to demonstrate the issue here: https://cru.ucdavis.edu/ckeditortest.cfm
The first instance of CKEditor resides within a div and behaves normally. The second instance is located in a table cell and exhibits the odd behavior.

Hopefully this will be an easy fix. Please let me know if you need any more information from me. :)  Love this plugin by the way... keep up the great work!

**Comment by w8tcha** [comment]
Is that still an issue? If yes please reopen again
