### ISSUE TITLE
cannot read property 'listeners' of undefined

### ISSUE THREAD

**Issue by rafinha90** [w8tcha/CKEditor-CodeMirror-Plugin#90]
Hi, I'm getting this error: `cannot read property 'listeners' of undefined`

And the line that is giving me problem is the line 925:
editor.container.getPrivate().events.contextmenu.listeners.splice(0, 1);

The problem happens if I build with CKBuilder and if I install it manually.
(I have Source Dialog installed, and tried withou it installed too)
Any lights?

**Comment by fmolinari** [comment]
Hi,

Having the same problem now. Any suggestion? I'm using backbone and requirejs although I'm loading ckeditor like this: <script type="text/javascript" src="app/scripts/libs/ckeditor/ckeditor.js"></script>

and inside config.js:
...
config.extraPlugins = 'indentblock,indent,codemirror';
...

Thank you

**Comment by w8tcha** [comment]
fixed with latest commit
