### ISSUE TITLE
CKeditor Inline mode: context menu not shown in firefox and chrome

### ISSUE THREAD

**Issue by bjbmedia** [w8tcha/CKEditor-CodeMirror-Plugin#91]
Hi, please take a look at the inline-example on

http://w8tcha.github.io/CKEditor-CodeMirror-Plugin/demoInline.html 

works fine with ie11, but with chrome or firefox, the ck context-menu on right-click is missing and the ff /chrome right-click menu is shown instead.

if you remove the codemirror-plugin, ck context-menu is shown as it should.

There is no error message shown in the console.

best regards

Bernd

**Comment by elebetsamer** [comment]
This issue has been driving me nuts for quite a while now. Would love to get a fix for it. For now, I'm just removing the codemirror plugin.

**Comment by c0y0tex** [comment]
Same here, context menu stops working as soon as codemirror is added.

**Comment by rzueger** [comment]
We've run into this too. Took us quite a while to figure out what caused the problems.

**Comment by upnavigator** [comment]
@rzueger. How did you solve it?

**Comment by rzueger** [comment]
@upnavigator Actually, we couldn't solve it - we had to remove the plugin. :(

**Comment by powerpoint** [comment]
Old issue, but I got the some problem, I'm using inline mode. 
I fixed the issue just on comment a single line in codemirror/plugins.js.

Check for line 924:
// editor.container.getPrivate().events.contextmenu.listeners.splice(0, 1);

This worked for me, maybe this has sideeffects, but I couldn't find any in my setup.

Kind Regards
M.

**Comment by w8tcha** [comment]
Okay thanks i change that
