### ISSUE TITLE
Numeric character reference is changed by minify.

### ISSUE THREAD

**Issue by nazonohito51** [w8tcha/CKEditor-CodeMirror-Plugin#92]
Hi. This is great plugin!

But, I found error.
Numeric character reference is changed by minify. Depending on the html encoding, it can not be displayed.

#### "▾" "▸"
 * before: https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/blob/d1e89d5d2fefbc3dce7a7f68d485882a40782fad/codemirror/js/addon/fold/foldgutter.css#L16
 * after: `CodeMirror-foldgutter-open:after{content:"▾"}`
   * in https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/blob/d1e89d5d2fefbc3dce7a7f68d485882a40782fad/codemirror/css/codemirror.min.css#L1

#### "↔"
 * before: https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/blob/d1e89d5d2fefbc3dce7a7f68d485882a40782fad/codemirror/js/addon/fold/foldcode.js#L130
 * after: `var u={rangeFinder:n.fold.auto,widget:"↔",minFoldSize:0,scanUp:!1};`
   * in https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/blob/d1e89d5d2fefbc3dce7a7f68d485882a40782fad/codemirror/js/codemirror.addons.min.js#L1

Is there any plan to fix it?

**Comment by w8tcha** [comment]
Ok looks like the author of the compressor don't call this one bug 

http://ajaxmin.codeplex.com/wikipage?title=Text%20Encoding

However i applied the changes to fix this...
