### ISSUE TITLE
Adding a <br /> tag throws a JS exception

### ISSUE THREAD

**Issue by kevjames3** [w8tcha/CKEditor-CodeMirror-Plugin#95]
Version 1.13
Replicable on the Demo page: http://w8tcha.github.io/CKEditor-CodeMirror-Plugin/demoFramed.html

Open a developer console window and you will see the following error

`Uncaught TypeError: codeMirror_Editor.closeTag is not a function`

Issues seems to be because the close tag addon is not included from CodeMirror, but I cannot completely identify the issue.

Also, this issue seems to be related to #79, but I wanted to open a new bug just in case

**Comment by w8tcha** [comment]
Well tecnically the close tag addon is included.

**Comment by kevjames3** [comment]
Yeah, hence my confusion.  I tried to dig deeper but I could not see anything that lined up

**Comment by w8tcha** [comment]
Well the demo is not up do date. Can you reproduce the issue with the latest version from github? because i can not reproduce it.

**Comment by w8tcha** [comment]
I updated the demo pages

**Comment by kevjames3** [comment]
Will look at my implementation to see if I can fix it
