### ISSUE TITLE
Braket match should omit brackets sourrounded by "

### ISSUE THREAD

**Issue by arbyter1** [w8tcha/CKEditor-CodeMirror-Plugin#97]
Thank you for this great plugin.
I am asking for a enhancement:
having a string like
put('this is my funny string :-) ')  will lead to a mismatched braket-count.
My succestion: any bracket within sourrounding " or ' should be treated as text, not bracket.

Thank you

**Comment by w8tcha** [comment]
Sorry for the very late reply, but i think requests for enhancements  of codemirror features should be requested in the CodeMirror Repository

https://github.com/codemirror/CodeMirror/issues
