### ISSUE TITLE
with textselection plugin, when switching from wysiwyg to codemirror with text selected, cursor should be hidden.

### ISSUE THREAD

**Issue by sirtet** [w8tcha/CKEditor-CodeMirror-Plugin#98]
Maybe it's a codemirror bug?
By function, everything works as expected, but there's a cursor that should not be there.
When switching to code view, the previously selected text stays selected as expected from the textselection plugin. But at the end of the selected area there's a cursor blinking, which should be hidden as long as there's something selected.

I get this with ckeditor 4.5.5 and the latest codemirror and textselection plugins, pulled via git clone.
I am not sure, but i think this is worked correctly before (ck 4.3.2 and corresponding plugins).

**Comment by w8tcha** [comment]
Why you think that this is a bug? that really is the default behavoir
